apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      #initContainers:
      #- name: app-web
      #  image: busybox:1.31.0
      #  command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      #  volumeMounts:
      #  - name: app
      #    mountPath: /app
      containers:
      - name: web
        image: cracit/web:simple
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
        #volumeMounts:
        #- name: app
        #  mountPath: /app
      #volumes:
      #- name: app
      #  emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
